Importing Libraries

In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv("../data/data.csv")
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [7]:
df.head() #displays first 5 entries
#df = pd.read_excel("../data/data.xlsx", sheet_name = "Sheet1") - for excel based dataset

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [9]:
df.shape

(10, 4)

In [10]:
df.dtypes

Country          str
Age          float64
Salary       float64
Purchased        str
dtype: object

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     str
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     str
dtypes: float64(2), str(2)
memory usage: 452.0 bytes

In [12]:
df.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [13]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
#split indepedent variables
#loc uses labels
#iloc uses integer positions (numbers from 0 to the length of data)

df
x = df.iloc[:, :-1].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [17]:
#split dependent variable
y = df.iloc[:,-1].values
y

<StringArray>
['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str

Taking care of missing data

In [27]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

# 1. Load your dataset
df = pd.read_csv('../data/data.csv')

# 2. Convert the dataframe into a 2D NumPy array 
# (Make sure you don't select just a single column, which makes it 1D)
x = df.values  

# 3. Now run your imputer code safely
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

# 4. View the result
print(x)

[['France' 44.0 72000.0 'No']
 ['Spain' 27.0 48000.0 'Yes']
 ['Germany' 30.0 54000.0 'No']
 ['Spain' 38.0 61000.0 'No']
 ['Germany' 40.0 63777.77777777778 'Yes']
 ['France' 35.0 58000.0 'Yes']
 ['Spain' 38.77777777777778 52000.0 'No']
 ['France' 48.0 79000.0 'Yes']
 ['Germany' 50.0 83000.0 'No']
 ['France' 37.0 67000.0 'Yes']]

In [ ]:
#encoding categorical data
#encoding the independent variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x = LabelEncoder()
x[:,0] = labelencoder_x.fit_transform(x[:,0])
print(x)

[[0 44.0 72000.0 'No']
 [2 27.0 48000.0 'Yes']
 [1 30.0 54000.0 'No']
 [2 38.0 61000.0 'No']
 [1 40.0 63777.77777777778 'Yes']
 [0 35.0 58000.0 'Yes']
 [2 38.77777777777778 52000.0 'No']
 [0 48.0 79000.0 'Yes']
 [1 50.0 83000.0 'No']
 [0 37.0 67000.0 'Yes']]

In [ ]:
#endoing the independent variable
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Country", OneHotEncoder(),[0])], remainder = "passthrough")
x = ct.fit_transform(x)

x.astype(int)

In [33]:
#split data into training and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.2, random_state=45)

In [34]:
x_test

array([[1.0, 0.0, 1.0, 0.0, 30.0, 54000.0, 'No'],
       [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778, 'Yes']], dtype=object)

In [37]:
#feature scaling
#sc_x = (x[1] - mean) / standard deviation
from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()

# Only scale columns 1 and 2 (leave the text columns untouched)
x_train[:, 1:3] = sc_x.fit_transform(x_train[:, 1:3])
x_test[:, 1:3] = sc_x.transform(x_test[:, 1:3])

In [38]:
x_train

array([[1.0, -1.0, -0.3779644730092272, 1.0, 27.0, 48000.0, 'Yes'],
       [1.0, -1.0, 2.6457513110645903, 0.0, 50.0, 83000.0, 'No'],
       [0.0, 1.0, -0.3779644730092272, 0.0, 37.0, 67000.0, 'Yes'],
       [1.0, -1.0, -0.3779644730092272, 1.0, 38.77777777777778, 52000.0,
        'No'],
       [0.0, 1.0, -0.3779644730092272, 0.0, 35.0, 58000.0, 'Yes'],
       [0.0, 1.0, -0.3779644730092272, 0.0, 48.0, 79000.0, 'Yes'],
       [0.0, 1.0, -0.3779644730092272, 0.0, 44.0, 72000.0, 'No'],
       [1.0, -1.0, -0.3779644730092272, 1.0, 38.0, 61000.0, 'No']],
      dtype=object)